name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  pie_chart: ^5.4.0


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.1
  intl: ^0.18.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  dropdown_button2: ^2.3.9
  json_annotation: ^4.8.1
  email_validator: ^2.1.17
  logger: ^2.2.0
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http_interceptor: ^2.0.0-beta.8
  fluttertoast: ^8.2.5
  web: 0.5.0
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.0
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  jwt_decoder: ^2.0.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.6
  mvvm_riverpod: ^1.2.0
  flutter_dotenv: ^5.1.0
  loading_animation_widget: ^1.2.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  test: ^1.24.9

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/banners/
    - assets/buttons/
    - assets/icons/
    - assets/logos/
    - assets/profiles/
    - .env
